### ISSUE TITLE
Some files missing in calibration folder

### ISSUE THREAD

**Issue by rizgiak** [NimbRo/nimbro-op-ros#2]
Hi, i'm interested in your research about nimbro op, but when i started build this source some files is missing, like `EnumerateCameraParams.h` and `CalibrationLUT.h`. Many thanks if you could give us complete code of this robot.

Thanks,

**Comment by pallgeuer** [comment]
Hi,

Those header files that you are supposedly missing indicate that there's something up with your build environment. Are you using catkin_make?

Those header files are automatically generated during the build process based on message and service files that are in the codebase, for example:

[EnumerateCameraParams.srv](https://github.com/NimbRo/nimbro-op-ros/blob/master/src/nimbro/cv/calibration/srv/EnumerateCameraParams.srv)
[CalibrationLUT.msg](https://github.com/NimbRo/nimbro-op-ros/blob/master/src/nimbro/cv/calibration/msg/CalibrationLUT.msg)

But there are many more, as no doubt you are seeing.

Regards,
Philipp
